services:
  mysql:
    image: mysql:8.0
    container_name: sandbox-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - sandbox-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sandbox-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: sandbox-mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - sandbox-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.rfess.fr`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$2y$05$wnqSpZwdqmSKRzhl5cmbKu3Vn1u8riQP2E9YQ6LWa8nK44jP1sjP6"

volumes:
  mysql-data:

networks:
  sandbox-network:
    external: true
